create table roles (
    id bigint generated by default as identity,
    name varchar(60),
    primary key (id)
);

create table rpc_data (
    id integer generated by default as identity,
    data_key varchar(255),
    data_value text,
    tenant varchar(255),
    token varchar(255),
    user_id bigint,
    primary key (id)
);

create table user_roles (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id)
);

create table users (
    id bigint generated by default as identity,
    name varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (id)
);